### ISSUE TITLE
neko -s silently exists

### ISSUE THREAD

**Issue by prologic** [adammathes/neko#1]
Is this suppose to happen?

```
prologic@Jamess-MacBook
Sun Jun 17 00:32:27
~/.neko
 0
$ neko -v -s
starting web server at 127.0.0.0.1:4994

prologic@Jamess-MacBook
Sun Jun 17 00:32:41
~/.neko
 0
$
```

**Comment by adammathes** [comment]
No, that's not supposed to happen.

Can you share what your config is?

It might be failing to connect to the DB (or the tables aren't there) and failing without a decent error message. Or maybe it's not binding to the port.

I updated the web server to log fatal errors to try and help debug if you don't mind rebuilding.

**Comment by prologic** [comment]
Works
